find_package(glm CONFIG REQUIRED)
add_definitions(-DGLM_FORCE_RADIANS)
add_definitions(-DGLM_FORCE_DEPTH_ZERO_TO_ONE)
add_definitions(-DGLM_ENABLE_EXPERIMENTAL)

if(WIN32)
    SET(HGL_GLM_LIB glm::glm)
else()
    SET(HGL_GLM_LIB GLM)
endif()
