if(APPLE)
    set(HGL_BITS 64)
else()
    if(ANDROID)
        if(ANDROID_ABI MATCHES ".*64.*")
            set(HGL_BITS 64)
        else()
            set(HGL_BITS 32)
        endif()
    else()
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(HGL_BITS 64)
        else()
            set(HGL_BITS 32)
        endif()
    endif()
endif()

if(HGL_BITS EQUAL 32)
    add_compile_definitions(HGL_32_BITS)
    add_compile_definitions(HGL_POINTER_UINT=uint32)
else()
    add_compile_definitions(HGL_64_BITS)
    add_compile_definitions(HGL_POINTER_UINT=uint64)
endif()

message("System is ${HGL_BITS} Bit")

