include(compiler)
include(system_bit)
include(version)
include(output_path)
include(cm_modules)

macro(use_cm_module module)
    add_subdirectory(CM${module})
    include(CM${module}/path_config.cmake)
    include_directories(CM${module}/inc)
endmacro()

macro(set_debugger_directory project path)
    set_target_properties(${project} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY ${path})
endmacro()
